name: Update Registry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip update')"
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          pip install -e git+https://github.com/network-wrangler/network_wrangler.git@main#egg=network_wrangler
          python update_registry.py

      - name: commit files
        run: |
          git config --local user.email "github-actions[bot]"
          git config --local user.name "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --allow-empty -m "GitHub Action automated registry update" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
